# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terragrunt-poc-2023"
    dynamodb_table = "terragrunt-poc"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "eu-west-2"
  }
}
