# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
    backend "s3" {
        bucket  = "terraform-statefiles-aws-vpc-20230103"
        key     = "./terraform.tfstate"
        region  = "us-east-1"
        encrypt = true
        dynamodb_table = "terraform-statefiles-aws-vpc-20230103"
    }
}
